### ISSUE TITLE
Infer type of None

### ISSUE THREAD

**Issue by OliverJAsh** [jiaweihli/monapt#11]
Is it possible to infer the type of `None` when used alongside `Some`?

E.g. in Scala:

``` scala
scala> def x = (a: Int) => if (a > 5) Some(5) else None
x: Int => Option[Int]
```

In TypeScript:

``` ts
const x = (a: number) => (a > 5) ? Option(5) : None
```

`x` here is of type `(a: number) => Option<any>`, because None is typed as `Option<any>`.

I wonder if it's possible to infer the generic type of `None` here from the usage of `Option` in the same function?

**Comment by jiaweihli** [comment]
This should be possible once TypeScript 2.0 lands.

`None` being typed as `Option<any>` is wrong, because `any` is the supertype of all types, rather than the subtype of all types.

Typescript 2.0 is getting a [`never`](https://github.com/Microsoft/TypeScript/pull/8652) type that is a subtype of all types.

**Comment by OliverJAsh** [comment]
Will this mean you can do the equivalent of `def x = (a: Int) => if (a > 5) Some(5) else None`? E.g. 

`x = (a: number): Option<number> => if (a > 5) { Option(5) } else { None }`

Currently I have to do 

`x = (a: number): Option<number> => if (a > 5) { Option(5) } else { None as Option<number> }`

**Comment by jiaweihli** [comment]
Yes, TypeScript 2.0 should allow the shorter form =)
